export interface Variation {
  id: string;
  imageUrl: string;
  label: string;
  fromNodeId: string;
  timestamp: number;
}

export enum NodeCategory {
  INPUT = 'input',
  TRANSFORM = 'transform',
  STYLE = 'style',
  RENDER = 'render',
  CUSTOM = 'custom'
}

export interface NodeDefinition {
  id: string;
  label: string;
  category: NodeCategory;
  description: string;
  customPrompt?: string; // User can override the default prompt
  x: number;
  y: number;
  parentId?: string;
  latestVariationId?: string; // ID of the latest variation generated by this node
}

export interface AppState {
  sourceImage: string | null; // Base64
  baseDescription: string;
  variations: Variation[];
  nodes: NodeDefinition[]; // Dynamic list of nodes
  isGenerating: Record<string, boolean>; // Map of nodeId -> boolean
  selectedVariationId: string | null; // For editing
  viewingVariationId: string | null; // For viewing large
}